export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as Presentation } from './Presentation'
export { default as Trade } from './TraderDisplay'
export { default as Features } from './Features'
export { default as Mining } from './StartMining'
export { default as Footer } from './Footer'
